// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/static/protos/domain.proto

package com.aleksandrbogomolov.domain;

public final class Domain {
  private Domain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeveloperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aleksandrbogomolov.domain.Developer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software> 
        getSoftList();
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    com.aleksandrbogomolov.domain.Domain.Developer.Software getSoft(int index);
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    int getSoftCount();
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    java.util.List<? extends com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder> 
        getSoftOrBuilderList();
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder getSoftOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.aleksandrbogomolov.domain.Developer}
   */
  public  static final class Developer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aleksandrbogomolov.domain.Developer)
      DeveloperOrBuilder {
    // Use Developer.newBuilder() to construct.
    private Developer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Developer() {
      id_ = 0;
      name_ = "";
      email_ = "";
      soft_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Developer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                soft_ = new java.util.ArrayList<com.aleksandrbogomolov.domain.Domain.Developer.Software>();
                mutable_bitField0_ |= 0x00000008;
              }
              soft_.add(
                  input.readMessage(com.aleksandrbogomolov.domain.Domain.Developer.Software.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          soft_ = java.util.Collections.unmodifiableList(soft_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aleksandrbogomolov.domain.Domain.Developer.class, com.aleksandrbogomolov.domain.Domain.Developer.Builder.class);
    }

    public interface SoftwareOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.aleksandrbogomolov.domain.Developer.Software)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code com.aleksandrbogomolov.domain.Developer.Software}
     */
    public  static final class Software extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.aleksandrbogomolov.domain.Developer.Software)
        SoftwareOrBuilder {
      // Use Software.newBuilder() to construct.
      private Software(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Software() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Software(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_Software_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aleksandrbogomolov.domain.Domain.Developer.Software.class, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.aleksandrbogomolov.domain.Domain.Developer.Software)) {
          return super.equals(obj);
        }
        com.aleksandrbogomolov.domain.Domain.Developer.Software other = (com.aleksandrbogomolov.domain.Domain.Developer.Software) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.aleksandrbogomolov.domain.Domain.Developer.Software parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.aleksandrbogomolov.domain.Domain.Developer.Software prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.aleksandrbogomolov.domain.Developer.Software}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.aleksandrbogomolov.domain.Developer.Software)
          com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_Software_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.aleksandrbogomolov.domain.Domain.Developer.Software.class, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder.class);
        }

        // Construct using com.aleksandrbogomolov.domain.Domain.Developer.Software.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor;
        }

        public com.aleksandrbogomolov.domain.Domain.Developer.Software getDefaultInstanceForType() {
          return com.aleksandrbogomolov.domain.Domain.Developer.Software.getDefaultInstance();
        }

        public com.aleksandrbogomolov.domain.Domain.Developer.Software build() {
          com.aleksandrbogomolov.domain.Domain.Developer.Software result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.aleksandrbogomolov.domain.Domain.Developer.Software buildPartial() {
          com.aleksandrbogomolov.domain.Domain.Developer.Software result = new com.aleksandrbogomolov.domain.Domain.Developer.Software(this);
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.aleksandrbogomolov.domain.Domain.Developer.Software) {
            return mergeFrom((com.aleksandrbogomolov.domain.Domain.Developer.Software)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.aleksandrbogomolov.domain.Domain.Developer.Software other) {
          if (other == com.aleksandrbogomolov.domain.Domain.Developer.Software.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.aleksandrbogomolov.domain.Domain.Developer.Software parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.aleksandrbogomolov.domain.Domain.Developer.Software) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.aleksandrbogomolov.domain.Developer.Software)
      }

      // @@protoc_insertion_point(class_scope:com.aleksandrbogomolov.domain.Developer.Software)
      private static final com.aleksandrbogomolov.domain.Domain.Developer.Software DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.aleksandrbogomolov.domain.Domain.Developer.Software();
      }

      public static com.aleksandrbogomolov.domain.Domain.Developer.Software getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Software>
          PARSER = new com.google.protobuf.AbstractParser<Software>() {
        public Software parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Software(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Software> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Software> getParserForType() {
        return PARSER;
      }

      public com.aleksandrbogomolov.domain.Domain.Developer.Software getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOFT_FIELD_NUMBER = 4;
    private java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software> soft_;
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    public java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software> getSoftList() {
      return soft_;
    }
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    public java.util.List<? extends com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder> 
        getSoftOrBuilderList() {
      return soft_;
    }
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    public int getSoftCount() {
      return soft_.size();
    }
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    public com.aleksandrbogomolov.domain.Domain.Developer.Software getSoft(int index) {
      return soft_.get(index);
    }
    /**
     * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
     */
    public com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder getSoftOrBuilder(
        int index) {
      return soft_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < soft_.size(); i++) {
        output.writeMessage(4, soft_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < soft_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, soft_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aleksandrbogomolov.domain.Domain.Developer)) {
        return super.equals(obj);
      }
      com.aleksandrbogomolov.domain.Domain.Developer other = (com.aleksandrbogomolov.domain.Domain.Developer) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getSoftList()
          .equals(other.getSoftList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getSoftCount() > 0) {
        hash = (37 * hash) + SOFT_FIELD_NUMBER;
        hash = (53 * hash) + getSoftList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aleksandrbogomolov.domain.Domain.Developer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aleksandrbogomolov.domain.Domain.Developer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aleksandrbogomolov.domain.Developer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aleksandrbogomolov.domain.Developer)
        com.aleksandrbogomolov.domain.Domain.DeveloperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aleksandrbogomolov.domain.Domain.Developer.class, com.aleksandrbogomolov.domain.Domain.Developer.Builder.class);
      }

      // Construct using com.aleksandrbogomolov.domain.Domain.Developer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSoftFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        if (softBuilder_ == null) {
          soft_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          softBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aleksandrbogomolov.domain.Domain.internal_static_com_aleksandrbogomolov_domain_Developer_descriptor;
      }

      public com.aleksandrbogomolov.domain.Domain.Developer getDefaultInstanceForType() {
        return com.aleksandrbogomolov.domain.Domain.Developer.getDefaultInstance();
      }

      public com.aleksandrbogomolov.domain.Domain.Developer build() {
        com.aleksandrbogomolov.domain.Domain.Developer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aleksandrbogomolov.domain.Domain.Developer buildPartial() {
        com.aleksandrbogomolov.domain.Domain.Developer result = new com.aleksandrbogomolov.domain.Domain.Developer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        if (softBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            soft_ = java.util.Collections.unmodifiableList(soft_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.soft_ = soft_;
        } else {
          result.soft_ = softBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aleksandrbogomolov.domain.Domain.Developer) {
          return mergeFrom((com.aleksandrbogomolov.domain.Domain.Developer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aleksandrbogomolov.domain.Domain.Developer other) {
        if (other == com.aleksandrbogomolov.domain.Domain.Developer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (softBuilder_ == null) {
          if (!other.soft_.isEmpty()) {
            if (soft_.isEmpty()) {
              soft_ = other.soft_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureSoftIsMutable();
              soft_.addAll(other.soft_);
            }
            onChanged();
          }
        } else {
          if (!other.soft_.isEmpty()) {
            if (softBuilder_.isEmpty()) {
              softBuilder_.dispose();
              softBuilder_ = null;
              soft_ = other.soft_;
              bitField0_ = (bitField0_ & ~0x00000008);
              softBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSoftFieldBuilder() : null;
            } else {
              softBuilder_.addAllMessages(other.soft_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aleksandrbogomolov.domain.Domain.Developer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aleksandrbogomolov.domain.Domain.Developer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software> soft_ =
        java.util.Collections.emptyList();
      private void ensureSoftIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          soft_ = new java.util.ArrayList<com.aleksandrbogomolov.domain.Domain.Developer.Software>(soft_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aleksandrbogomolov.domain.Domain.Developer.Software, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder, com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder> softBuilder_;

      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software> getSoftList() {
        if (softBuilder_ == null) {
          return java.util.Collections.unmodifiableList(soft_);
        } else {
          return softBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public int getSoftCount() {
        if (softBuilder_ == null) {
          return soft_.size();
        } else {
          return softBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public com.aleksandrbogomolov.domain.Domain.Developer.Software getSoft(int index) {
        if (softBuilder_ == null) {
          return soft_.get(index);
        } else {
          return softBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder setSoft(
          int index, com.aleksandrbogomolov.domain.Domain.Developer.Software value) {
        if (softBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoftIsMutable();
          soft_.set(index, value);
          onChanged();
        } else {
          softBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder setSoft(
          int index, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder builderForValue) {
        if (softBuilder_ == null) {
          ensureSoftIsMutable();
          soft_.set(index, builderForValue.build());
          onChanged();
        } else {
          softBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder addSoft(com.aleksandrbogomolov.domain.Domain.Developer.Software value) {
        if (softBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoftIsMutable();
          soft_.add(value);
          onChanged();
        } else {
          softBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder addSoft(
          int index, com.aleksandrbogomolov.domain.Domain.Developer.Software value) {
        if (softBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSoftIsMutable();
          soft_.add(index, value);
          onChanged();
        } else {
          softBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder addSoft(
          com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder builderForValue) {
        if (softBuilder_ == null) {
          ensureSoftIsMutable();
          soft_.add(builderForValue.build());
          onChanged();
        } else {
          softBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder addSoft(
          int index, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder builderForValue) {
        if (softBuilder_ == null) {
          ensureSoftIsMutable();
          soft_.add(index, builderForValue.build());
          onChanged();
        } else {
          softBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder addAllSoft(
          java.lang.Iterable<? extends com.aleksandrbogomolov.domain.Domain.Developer.Software> values) {
        if (softBuilder_ == null) {
          ensureSoftIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, soft_);
          onChanged();
        } else {
          softBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder clearSoft() {
        if (softBuilder_ == null) {
          soft_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          softBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public Builder removeSoft(int index) {
        if (softBuilder_ == null) {
          ensureSoftIsMutable();
          soft_.remove(index);
          onChanged();
        } else {
          softBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder getSoftBuilder(
          int index) {
        return getSoftFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder getSoftOrBuilder(
          int index) {
        if (softBuilder_ == null) {
          return soft_.get(index);  } else {
          return softBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public java.util.List<? extends com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder> 
           getSoftOrBuilderList() {
        if (softBuilder_ != null) {
          return softBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(soft_);
        }
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder addSoftBuilder() {
        return getSoftFieldBuilder().addBuilder(
            com.aleksandrbogomolov.domain.Domain.Developer.Software.getDefaultInstance());
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder addSoftBuilder(
          int index) {
        return getSoftFieldBuilder().addBuilder(
            index, com.aleksandrbogomolov.domain.Domain.Developer.Software.getDefaultInstance());
      }
      /**
       * <code>repeated .com.aleksandrbogomolov.domain.Developer.Software soft = 4;</code>
       */
      public java.util.List<com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder> 
           getSoftBuilderList() {
        return getSoftFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aleksandrbogomolov.domain.Domain.Developer.Software, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder, com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder> 
          getSoftFieldBuilder() {
        if (softBuilder_ == null) {
          softBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.aleksandrbogomolov.domain.Domain.Developer.Software, com.aleksandrbogomolov.domain.Domain.Developer.Software.Builder, com.aleksandrbogomolov.domain.Domain.Developer.SoftwareOrBuilder>(
                  soft_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          soft_ = null;
        }
        return softBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aleksandrbogomolov.domain.Developer)
    }

    // @@protoc_insertion_point(class_scope:com.aleksandrbogomolov.domain.Developer)
    private static final com.aleksandrbogomolov.domain.Domain.Developer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aleksandrbogomolov.domain.Domain.Developer();
    }

    public static com.aleksandrbogomolov.domain.Domain.Developer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Developer>
        PARSER = new com.google.protobuf.AbstractParser<Developer>() {
      public Developer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Developer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Developer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Developer> getParserForType() {
      return PARSER;
    }

    public com.aleksandrbogomolov.domain.Domain.Developer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aleksandrbogomolov_domain_Developer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aleksandrbogomolov_domain_Developer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aleksandrbogomolov_domain_Developer_Software_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/static/protos/domai" +
      "n.proto\022\035com.aleksandrbogomolov.domain\"\217" +
      "\001\n\tDeveloper\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005email\030\003 \001(\t\022?\n\004soft\030\004 \003(\01321.com.aleksa" +
      "ndrbogomolov.domain.Developer.Software\032\030" +
      "\n\010Software\022\014\n\004name\030\001 \001(\tB\037\n\035com.aleksand" +
      "rbogomolov.domainb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aleksandrbogomolov_domain_Developer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aleksandrbogomolov_domain_Developer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aleksandrbogomolov_domain_Developer_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Soft", });
    internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor =
      internal_static_com_aleksandrbogomolov_domain_Developer_descriptor.getNestedTypes().get(0);
    internal_static_com_aleksandrbogomolov_domain_Developer_Software_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aleksandrbogomolov_domain_Developer_Software_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
